server:
  port: 18081
zk:
  url: 127.0.0.1:2181
  sessionTimeout: 15000
  connectTimeout: 30000
  namespace: user
  
spring:
  ### 配置Redis
  # Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 
    # 配置连接池
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 2000
    lettuce:
      shutdown-timeout: 0