server:
  port: 9033

### 应用名称
spring:
  application:
    name: sentinel-gateway
    
  cloud:
    gateway:
      routes: 
        - id: sentinel-feign-gateway
          # 路由转发
          uri: lb://sentinel-springcloud
          # uri: http://localhost:18082
          # 断言
          predicates:
            - Path=/**
    sentinel:
      transport:
        dashboard: localhost:9000

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9010/eureka
      
# 开启Sentinel对feign的支持
feign:
  sentinel:
    enabled: true